### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by andela-ekupara** [andela-hthuo/documents-app#4]
I like the simplicity of the app. However, in my usage I stumbled upon the following issues:
- [x] Clicking on profile requires 3 clicks to redirect a user to their profile
- [x]  When I click log out I am still able to see documents that should be visible only to logged in users
- [x] I should not have the ability to change the permissions for a document I didn't create. Though this is implemented on the server, a user is made to believe it is possible given the availability of the edit options on such documents.

**Comment by andela-ekupara** [comment]
The styling you have here:
```javascript
  expect(
    context.props.addDocument.withArgs(values).calledOnce
  ).to.be.true;
```

could be changed to:
```javascript
  expect(context.props.addDocument
    .withArgs(values).calledOnce).to.be.true;

**Comment by andela-hthuo** [comment]
I'll keep the old styling because I've used consistently and I think by not breaking the argument to `expect`, the code is easier to read.
