### ISSUE TITLE
Clear Button and Profile Button

### ISSUE THREAD

**Issue by andela-emabishi** [andela-hthuo/documents-app#8]
* It's unclear whether the clear button clears the contents of the list or clears the selection. Perhaps a `clear selection` button would be clearer.
* Profile button seems non-functional.

**Comment by andela-hthuo** [comment]
The actual button text is `Clear Filters` but it's is trimmed when there isn't enough space. However I think `Clear` works too because it only takes one click for a user to discover what it does.
