### ISSUE TITLE
Form validation errors.

### ISSUE THREAD

**Issue by Waiyaki** [andela-hthuo/documents-app#9]
- [ ] The login and sign up fields are showing me validation errors even before I've typed anything into them.

- [x] The first name and last name fields seem coupled such that if I'm editing one field and happen to delete it's contents, the error message appears even for the other field.

<img width="950" alt="screen shot 2016-08-19 at 00 41 19" src="https://cloud.githubusercontent.com/assets/10425350/17791755/b75e6320-65a5-11e6-8ad5-bc67444edb69.png">

**Comment by andela-hthuo** [comment]
The validation errors before you've started typing are by design to serve as indicators of which fields are required.

**Comment by Waiyaki** [comment]
Do you think that makes for a good UX?

**Comment by andela-hthuo** [comment]
It's not the best but I think it's better than no indication.
